compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.17.1.cjs

packageExtensions:
  "@react-native/eslint-config@*":
    dependencies:
      typescript: "^5.8.3"
  "@react-native/jest-preset@*":
    dependencies:
      "@babel/core": "^7.25.2"
  "babel-plugin-transform-flow-enums@*":
    dependencies:
      "@babel/core": "^7.25.2"
